# Don't print a new line at the start of the prompt
add_newline = false

# Character package
[character]     
success_symbol = "[~>](bold green)"
error_symbol = "[~>](bold red)"

# Username display
[username]
show_always = true

# line break in prompt
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable Python module
[python]
disabled = true

# Disable Rust module
[rust]
disabled = true
