# Don't print a new line at the start of the prompt
add_newline = false

# Character package
[character]     
success_symbol = "[\u03BB](bold green)"
error_symbol = "[\u03BB](bold red)"

# Username display
[username]
show_always = true

# hostname module
[hostname]
ssh_only = true
style = "bold blue"

# line break in prompt
[line_break]
disabled = true

# Disable the package module, hiding it from the prompt completely
[package]
disabled = true

# Disable Python module
[python]
disabled = false

# Disable Rust module
[rust]
disabled = false
